service: gifbucket-server

frameworkVersion: ">=1.1.0"

custom:
  bucket: ${env:REACT_APP_S3_BUCKET}

provider:
  name: aws
  runtime: nodejs8.10
  stage: live
  region: ${env:REACT_APP_S3_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  save:
    handler: handler.http
    events:
      - http:
          method: post
          path: "gifs/create"
          cors: 
            origins:
              - "http://localhost:3000"
              - "https://gif.joshmcarthur.com"
            headers:
              - "X-Api-Key"
              - "Content-Type"
              - "Accept"
            allowCredentials: false
          request:
            parameters:
              querystrings:
                url: true
    environment:
      BUCKET: ${self:custom.bucket}
